services:
    david63.disclaimer.listener:
        class: david63\disclaimer\event\listener
        arguments:
            - '@config'
            - '@template'
            - '@language'
        tags:
            - { name: event.listener }
